export const drivePreview = (id: string) => `https://drive.google.com/file/d/${id}/preview`;
export const driveView = (id: string) => `https://drive.google.com/file/d/${id}/view`;
export const driveThumbnail = (id: string) => `https://drive.google.com/thumbnail?id=${id}&sz=w1600`;
export const driveDownload = (id: string) => `https://drive.google.com/uc?export=download&id=${id}`;
export const driveVideoProxy = (id: string) => `/api/drive-video?id=${id}`;

export const proofOfWork = [
  {
    id: 'showreel',
    title: 'Showreel',
    category: 'Overview Reel',
    format: 'Portfolio intro',
    role: 'Agency Reel',
    year: '2026',
    tag: 'SHOWREEL',
    driveId: '1iCZBzE5uQvjKgl2JFIpc6k5Nu1C34mVa',
    previewSrc: '/previews/showreel.mp4',
    posterSrc: '/previews/showreel.jpg',
    description: 'A compact overview reel for introducing InkFrame Films in outbound messages and pitch calls.',
    accent: '#D4A03C',
    size: 'wide',
  },
  {
    id: 'aza-fashion',
    title: 'Aza Fashion',
    category: 'Fashion Campaign',
    format: 'Vertical 4K',
    role: 'Fashion · Editorial',
    year: '2026',
    tag: 'FASHION FILM',
    driveId: '1XEkjR0wybxPfdHcvR0eRpYEwKRI75O40',
    previewSrc: '/previews/aza-fashion.mp4',
    posterSrc: '/previews/aza-fashion.jpg',
    description: 'Premium editorial campaign visual for luxury fashion and designer retail outreach.',
    accent: '#E6D7C3',
    size: 'tall',
  },
  {
    id: 'swiss-beauty',
    title: 'Swiss Beauty',
    category: 'Beauty Film',
    format: 'Vertical 4K',
    role: 'Beauty · About Film',
    year: '2026',
    tag: 'BEAUTY CAMPAIGN',
    driveId: '13e1DpsZ6nzmLhXnEevjoEzivj9aLDV-s',
    previewSrc: '/previews/swiss-beauty.mp4',
    posterSrc: '/previews/swiss-beauty.jpg',
    description: 'Beauty/about-film style piece for cosmetics, skincare, and personal-care brands.',
    accent: '#F0A7B7',
    size: 'tall',
  },
  {
    id: 'caneza',
    title: 'Caneza',
    category: 'Brand Video',
    format: 'Horizontal',
    role: 'Product · Storytelling',
    year: '2026',
    tag: 'BRAND FILM',
    driveId: '1DV0mqQfHvjdxA6S14lms9817eKqU48vS',
    previewSrc: '/previews/caneza.mp4',
    posterSrc: '/previews/caneza.jpg',
    description: 'Cinematic product-led storytelling for refined digital campaigns.',
    accent: '#8AB7B4',
    size: 'wide',
  },
  {
    id: 'beyond-the-glass',
    title: 'Beyond The Glass',
    category: 'Concept Piece',
    format: 'Compact frame',
    role: 'Concept · Worldbuilding',
    year: '2026',
    tag: 'VISUAL EXPERIMENT',
    driveId: '1h8zGYzt2N9DzDW5dLpI9ln4P-NngirpW',
    previewSrc: '/previews/beyond-the-glass.mp4',
    posterSrc: '/previews/beyond-the-glass.jpg',
    description: 'Creative direction, atmosphere, and AI-led visual worldbuilding in an experimental frame.',
    accent: '#8CA6D9',
    size: 'standard',
  },
  {
    id: 'melting-clock',
    title: 'Melting Clock',
    category: 'Surreal Film',
    format: '4K concept',
    role: 'Surreal · Object Film',
    year: '2026',
    tag: 'AI CONCEPT',
    driveId: '1U-_khWbcj4-ZJprV5-R3h2xzAF6hpjEW',
    previewSrc: '/previews/melting-clock.mp4',
    posterSrc: '/previews/melting-clock.jpg',
    description: 'AI visual experimentation, art direction, and cinematic object transformation.',
    accent: '#CDA6F7',
    size: 'standard',
  },
  {
    id: 'ferrari-concept',
    title: 'Ferrari Concept',
    category: 'Automotive Spot',
    format: 'Luxury concept',
    role: 'Automotive · Performance',
    year: '2026',
    tag: 'AUTOMOTIVE SPOT',
    driveId: '1Rh7zSdF-aWS2vy9_xbDBa1Jzy7dVfnOu',
    previewSrc: '/previews/ferrari-concept.mp4',
    posterSrc: '/previews/ferrari-concept.jpg',
    description: 'High-energy luxury, performance, and aspirational automotive storytelling.',
    accent: '#D62F2F',
    size: 'wide',
  },
  {
    id: 'theft',
    title: 'Theft',
    category: 'Narrative Action',
    format: 'Concept video',
    role: 'Narrative · Action',
    year: '2026',
    tag: 'SHORT CONCEPT',
    driveId: '1XbXK9TbBlVe_qazn4mphpMdHMM7M00GZ',
    previewSrc: '/previews/theft.mp4',
    posterSrc: '/previews/theft.jpg',
    description: 'Longer-form pacing, tension, and scene continuity for narrative/action concepts.',
    accent: '#5A8A8A',
    size: 'standard',
  },
] as const;

export const services = [
  'Brand films and launch reels',
  'AI product commercials',
  'Fashion and beauty campaign videos',
  'Automotive concept spots',
  'Short-form social ads',
  'Surreal visual experiments and mood films',
  'Showreels for pitches, decks, and outbound client outreach',
  'Instagram-first content systems for social pages, creators, and character-led brands',
];

export const bestFitClients = [
  'Fashion labels and designer marketplaces',
  'Beauty, skincare, and cosmetics brands',
  'Automotive and luxury lifestyle brands',
  'Consumer products launching new campaigns',
  'Agencies that need fast concept films or AI-assisted production',
];

export const servicePillars = [
  {
    num: '01',
    title: 'AI Product Commercials',
    desc: 'Campaign-ready product films with cinematic lighting, controlled art direction, and quick creative iteration.',
    deliverables: ['Concept routes', 'AI-generated sequences', 'Compositing', 'Web and social cutdowns'],
  },
  {
    num: '02',
    title: 'Fashion And Beauty Films',
    desc: 'Editorial visuals for luxury, cosmetics, skincare, personal care, and designer retail brands.',
    deliverables: ['Launch reels', 'Vertical 4K assets', 'Mood films', 'Campaign treatments'],
  },
  {
    num: '03',
    title: 'Automotive And Luxury Concepts',
    desc: 'Performance-led spots and aspirational product worlds for brands that need atmosphere before a full shoot.',
    deliverables: ['Concept films', 'Hero shots', 'Pitch visuals', 'Brand worlds'],
  },
  {
    num: '04',
    title: 'Social Content Systems',
    desc: 'Repeatable video pipelines for Instagram-first pages, creators, character-led IP, and always-on brand content.',
    deliverables: ['Short-form batches', 'Visual rules', 'Posting-ready edits', 'Ongoing creative consistency'],
  },
];

export const auraReport = {
  reportingPeriod: 'February 12, 2026 - May 13, 2026',
  reportingWindow: '90 days',
  profileName: 'Aura Kid',
  handle: '@aurakidzzz',
  totalPosts: '62',
  followers: '76,733',
  newFollowers: '15,255',
  followerGrowth: '+24%',
  views: '112,945,046',
  averageReach: '279,116.5',
  averageLikes: '9,276.5',
  averageComments: '39.5',
  averageEngagement: '3.5%',
  storyViews: '7,146',
  storyReach: '5,969',
  storyReplies: '14',
  mostActiveDay: 'Tuesday, May 5, 2026',
  timezone: 'Asia/Calcutta (GMT+5:30)',
  topCountries: [
    'Brazil 32%',
    'Turkey 14%',
    'Japan 9.1%',
    'India 9.1%',
    'Argentina 9.1%',
  ],
  audienceAge: [
    '25-34: 36%',
    '35-44: 36%',
    '18-24: 14%',
    '45-54: 9.1%',
    '55-64: 4.5%',
  ],
  audienceGender: [
    'Female 64%',
    'Male 9.1%',
    'Prefer not to say 27%',
  ],
  topPostPerformance: [
    'Top post reached 2M with 99K likes and 267 comments',
    'Another top post reached 1.8M with 148K likes and 8.4% engagement',
    'Top story examples reached up to 10K views and 8.1K reach',
  ],
} as const;

export const auraHighlights = [
  'Complete short-form video content pipeline for an Instagram-native brand',
  '15,255 new followers and 112,945,046 views during the 90-day reporting period',
  'Average post performance of 279,116.5 reach, 9,276.5 likes, and 3.5% engagement',
  'Audience clustered around ages 25-44, with strongest concentration in Brazil, Turkey, Japan, India, and Argentina',
];

export const outreachCopy = `Hi [Name],

We are InkFrame Films, an AI-first video agency creating cinematic ads, fashion films, product launches, and concept reels for brands that want premium visuals without traditional production timelines.

If your team is exploring campaign films, AI product commercials, or high-performing social video, we would love to share a few ideas tailored to your brand.

Best,
InkFrame Films`;
